version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-sql
    container_name: "container-db-psql"
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "patata"
    ports:
      - "5432:5432"
    volumes:
      - ./sql/db-volume:/var/lib/postgresql/data
      #  falta hacer mvn package -DskipTests
      # backoffice:
      #   build:
      #     context: .
      #     dockerfile: ./back-office/src/main/docker/Dockerfile.jvm
      #   container_name: "container-backoffice"
      #   ports:
      #     - "8080:8080"
      # depends_on:
      # - db
      # volumes:
      #   - ./backoffice:/usr/src/app
      #     # command: ["npm", "run", "dev"]
      # frontoffice:
      #   build:
      #     context: .
      #     dockerfile: ./front-office/src/main/docker/Dockerfile.jvm
      #   container_name: "container-frontoffice"
      #   ports:
      #     - "8080:8081"
  model:
		build:
			context: .
			dockerfile: Dockerfile-model
		container_name: "container-model-python"
		environment:
		ports: 
			- "4321:4321"
		volumes:
			- ./model/model-volume:/./app
		
