FROM postgres
ENV POSTGRES_USER="user"
ENV POSTGRES_PASSWORD="patata"
ENV PGDATA=/var/lib/postgresql/data/
EXPOSE 5432/tcp
RUN mkdir -p /var/sql_scripts
COPY ./sql/create-db.sh /docker-entrypoint-initdb.d/
COPY ./sql/sql_scripts /var/sql_scripts
