#FROM python:3.8
FROM tensorflow/tensorflow:latest
WORKDIR /app
EXPOSE 4321/tcp
COPY ./model/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /app
CMD ["python", "main.py"]
