INSERT INTO breed (id, is_exotic, name, space_need, activity_need, alimentation_need, dangerous_race, time_dedication_need) VALUES
(1, TRUE, 'Afghan Hound', 15, 'Energetic', 'Dignified, Profoundly Loyal, Aristocratic', FALSE, '0.2'),
(2, FALSE, 'French Bulldog', 8, 'Calm', 'Adaptable, Playful, Smart', TRUE, '0.6'),
(3, FALSE, 'Akita', 24, 'Energetic', 'Courageous, Dignified, Profoundly Loyal', TRUE, '0.6'),
(4, FALSE, 'Alaskan Malamute', 21, 'Energetic', 'Affectionate, Loyal, Playful', FALSE, '0.8'),
(5, FALSE, 'American Staffordshire Terrier', 14, 'Regular Exercise', 'Confident, Smart, Good-Natured', TRUE, '0.6'),
(6, FALSE, 'Chihuahua', 2, 'Regular Exercise', 'Charming, Graceful, Sassy', TRUE, '0.6'),
(7, FALSE, 'Dogo Argentino', 25, 'Needs Lots of Activity', 'Friendly, Cheerful, Humble', TRUE, '1.6'),
(8, FALSE, 'Australian Shepherd', 13, 'Energetic', 'Smart, Work-Oriented, Exuberant', TRUE, '0.6'),
(9, FALSE, 'Basset Hound', 13, 'Couch Potato', 'Charming, Patient, Low-Key', FALSE, '0.8'),
(10, FALSE, 'Beagle', 5, 'Energetic', 'Friendly, Curious, Merry', FALSE, '0.8'),
(11, FALSE, 'Poodle (Toy)', 1, 'Regular Exercise', 'Agile, Intelligent, Self-Confident', FALSE, '0.8'),
(12, FALSE, 'Siberian Husky', 12, 'Energetic', 'Loyal, Mischievous, Outgoing', FALSE, '0.8'),
(13, FALSE, 'Standard Schnauzer', 10, 'Regular Exercise', 'Fearless, Smart, Spirited', FALSE, '0.8'),
(14, FALSE, 'Yorkshire Terrier', 2, 'Regular Exercise', 'Affectionate, Sprightly, Tomboyish', FALSE, '0.8'),
(15, FALSE, 'Belgian Malinois', 15, 'Energetic', 'Confident, Smart, Hardworking', FALSE, '0.4'),
(16, FALSE, 'Bichon Frise', 4, 'Regular Exercise', 'Playful, Curious, Peppy', FALSE, '1.0'),
(17, FALSE, 'Border Collie', 10, 'Needs Lots of Activity', 'Affectionate, Smart, Energetic', FALSE, '0.4'),
(18, FALSE, 'Boston Terrier', 4, 'Regular Exercise', 'Friendly, Bright, Amusing', FALSE, '1.0'),
(19, FALSE, 'Boxer', 10, 'Energetic', 'Bright, Fun-Loving, Active', FALSE, '1.0'),
(20, FALSE, 'Bulldog', 12, 'Regular Exercise', 'Friendly, Courageous, Calm', FALSE, '0.8'),
(21, FALSE, 'Labrador Retriever', 17, 'Needs Lots of Activity', 'Friendly, Active, Outgoing', FALSE, '1.0'),
(22, FALSE, 'Cocker Spaniel', 6, 'Regular Exercise', 'Gentle, Smart, Happy', FALSE, '1.0'),
(23, FALSE, 'Dachshund', 5, 'Regular Exercise', 'Friendly, Curious, Spunky', FALSE, '0.6'),
(24, FALSE, 'Doberman Pinscher', 20, 'Needs Lots of Activity', 'Loyal, Fearless, Alert', FALSE, '0.6'),
(25, FALSE, 'English Cocker Spaniel', 8, 'Regular Exercise', 'Energetic, Merry, Responsive', FALSE, '0.8'),
(26, FALSE, 'English Cocker Spaniel', 8, 'Regular Exercise', 'Energetic, Merry, Responsive', FALSE, '0.8'),
(27, FALSE, 'Dutch Shepherd', 14, 'Needs Lots of Activity', 'Intelligent, Lively, Athletic', FALSE, '0.6'),
(28, FALSE, 'Golden Retriever', 17, 'Needs Lots of Activity', 'Friendly, Intelligent, Devoted', FALSE, '0.8'),
(29, FALSE, 'Great Dane', 36, 'Energetic', 'Friendly, Patient, Dependable', FALSE, '0.6'),
(30, FALSE, 'Russell Terrier', 3, 'Needs Lots of Activity', 'Alert, Inquisitive, Lively', FALSE, '0.8'),
(31, FALSE, 'Pekingese', 4, 'Calm', 'Affectionate, Loyal, Regal in Manner', FALSE, '0.4'),
(32, FALSE, 'Maltese', 2, 'Regular Exercise', 'Gentle, Playful, Charming', FALSE, '1.0'),
(33, FALSE, 'Miniature Schnauzer', 4, 'Regular Exercise', 'Friendly, Smart, Obedient', TRUE, '0.6'),
(34, FALSE, 'Shih Tzu', 3, 'Regular Exercise', 'Affectionate, Playful, Outgoing', FALSE, '0.8'),
(35, FALSE, 'Neapolitan Mastiff', 34, 'Regular Exercise', 'Loyal, Dignified, Watchful', FALSE, '0.2'),
(36, FALSE, 'Newfoundland', 32, 'Regular Exercise', 'Sweet, Patient, Devoted', FALSE, '0.8'),
(37, FALSE, 'Old English Sheepdog', 20, 'Regular Exercise', 'Adaptable, Gentle, Smart', TRUE, '0.6'),
(38, FALSE, 'Miniature Bull Terrier', 6, 'Energetic', 'Upbeat, Mischievous, Comical', TRUE, '0.6'),
(39, FALSE, 'Pug', 4, 'Regular Exercise', 'Charming, Mischievous, Loving', FALSE, '0.8'),
(40, FALSE, 'Parson Russell Terrier', 4, 'Needs Lots of Activity', 'Friendly, Clever, Athletic', FALSE, '0.8'),
(41, FALSE, 'Miniature Pinscher', 2, 'Regular Exercise', 'Fearless, Fun-Loving, Proud', TRUE, '0.6'),
(42, FALSE, 'Pomeranian', 1, 'Regular Exercise', 'Inquisitive, Bold, Lively', TRUE, '0.6'),
(43, FALSE, 'Rottweiler', 27, 'Regular Exercise', 'Loyal, Loving, Confident Guardian', FALSE, '0.4'),
(44, FALSE, 'Collie', 16, 'Regular Exercise', 'Devoted, Graceful, Proud', FALSE, '0.8'),
(45, FALSE, 'Samoyed', 12, 'Energetic', 'Adaptable, Friendly, Gentle', FALSE, '0.8'),
(46, FALSE, 'Scottish Terrier', 5, 'Regular Exercise', 'Confident, Independent, Spirited', TRUE, '0.6'),
(47, FALSE, 'Chinese Shar-Pei', 14, 'Regular Exercise', 'Loyal, Independent, Calm', FALSE, '0.4'),
(48, FALSE, 'Saint Bernard', 38, 'Regular Exercise', 'Playful, Charming, Inquisitive', FALSE, '0.8'),
(49, FALSE, 'West Highland White Terrier', 5, 'Regular Exercise', 'Loyal, Happy, Entertaining', FALSE, '0.8'),
(50, FALSE, 'Bull Terrier', 15, 'Energetic', 'Playful, Charming, Mischievous', FALSE, '0.8'),
(51, FALSE, 'Bullmastiff', 30, 'Energetic', 'Affectionate, Loyal, Brave', TRUE, '0.6'),
(52, FALSE, 'Cane Corso', 0, 'Energetic', 'Affectionate, Intelligent, Majestic', TRUE, '0.6'),
(53, FALSE, 'Chow Chow', 15, 'Regular Exercise', 'Dignified, Bright, Serious-Minded', FALSE, '0.4'),
(54, FALSE, 'Bernese Mountain Dog', 23, 'Energetic', 'Good-Natured, Calm, Strong', FALSE, '0.4'),
(55, FALSE, 'Central Asian Shepherd Dog', 26, 'Calm', 'Independent, Courageous, Self-Confident', FALSE, '0.2');